# Generated by Django 6.0.4 on 2026-04-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telephone_number',
            field=models.CharField(default=998915625572, max_length=20, unique=True, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
    ]
